create function pg_temp.assert_true(value boolean, message text) returns void language plpgsql as $$ begin if value is distinct from true then raise exception '%',message; end if; end $$;
insert into ticket_submissions(id) values('00000000-0000-4000-8000-000000000001');
select pg_temp.assert_true(ticket_recovery_snapshot('submission','00000000-0000-4000-8000-000000000001')->>'mode'='payment','consent-complete uses payment only');
select pg_temp.assert_true(ticket_recovery_snapshot('submission','00000000-0000-4000-8000-000000000001')->>'eligible'='true','submitted ticket eligible');
update ticket_submissions set consent_form_path=null;
select pg_temp.assert_true(ticket_recovery_snapshot('submission','00000000-0000-4000-8000-000000000001')->>'mode'='checkout','both missing uses checkout');
update ticket_submissions set representation_paid_at=now();
select pg_temp.assert_true(ticket_recovery_snapshot('submission','00000000-0000-4000-8000-000000000001')->>'mode'='consent','paid case needs only consent');
update ticket_submissions set consent_form_path='consent.pdf';
select pg_temp.assert_true(ticket_recovery_snapshot('submission','00000000-0000-4000-8000-000000000001')->>'reason'='complete','complete stopped');
update ticket_submissions set representation_paid_at=null,ticket_number='';
select pg_temp.assert_true(ticket_recovery_snapshot('submission','00000000-0000-4000-8000-000000000001')->>'reason'='ticket_number_required','missing number held');
update ticket_submissions set ticket_number='B12345678C',intake_review_status='needs_review';
select pg_temp.assert_true(ticket_recovery_snapshot('submission','00000000-0000-4000-8000-000000000001')->>'reason'='ticket_review_required','OCR requires review');
update ticket_submissions set intake_review_status='ready';
insert into service_orders(email,payment_status) values('customer@example.com','paid');
select pg_temp.assert_true(ticket_recovery_snapshot('submission','00000000-0000-4000-8000-000000000001')->>'reason'='service_order_matching_required','unmatched payment held');
delete from service_orders;
insert into idr_checkout_intents(ticket_submission_id,status) values('00000000-0000-4000-8000-000000000001','paid');
select pg_temp.assert_true(ticket_recovery_snapshot('submission','00000000-0000-4000-8000-000000000001')->>'reason'='complete','ledger paid independently of status');
delete from idr_checkout_intents;
insert into ticket_intake_drafts(id) values('00000000-0000-4000-8000-000000000002');
select pg_temp.assert_true(ticket_recovery_snapshot('draft','00000000-0000-4000-8000-000000000002')->>'has_consent'='true','restarted draft resolves consent by ticket and email');
update ticket_intake_drafts set draft_data='{"ticketNumber":"B99999999C","smsOptIn":false}';
select pg_temp.assert_true(ticket_recovery_snapshot('draft','00000000-0000-4000-8000-000000000002')->>'has_consent'='false','different ticket never inherits consent');
select pg_temp.assert_true(enqueue_ticket_recovery()=0,'disabled worker enrolls nobody');
do $$begin
  begin perform configure_ticket_recovery(true,null); raise exception 'address was not enforced'; exception when check_violation then null; end;
end$$;
select configure_ticket_recovery(true,'123 Test Street, Calgary, AB');
select pg_temp.assert_true((select not enabled from abandoned_ticket_email_settings),'old worker disabled on activation');
insert into abandoned_ticket_emails values('00000000-0000-4000-8000-000000000002','sent',now()-interval '4 days',null);
select enqueue_ticket_recovery(); select enqueue_ticket_recovery();
select pg_temp.assert_true((select count(*)=12 from ticket_recovery_events),'enrollment idempotent');
select pg_temp.assert_true((select count(*)=1 from ticket_recovery_events where status='historical'),'prior email consumes first stage');
select pg_temp.assert_true((select min(due_at) >= (select activated_at from ticket_recovery_settings) from ticket_recovery_events),'no burst of old stages');
select pg_temp.assert_true((select max(due_at)-min(due_at)=interval '6 days' from ticket_recovery_events where source_kind='submission'),'backlog stages spaced');
-- Claim/attempt RPCs enforce fresh eligibility, durable attempt and unique recipient-ticket-stage.
do $$declare e ticket_recovery_events; snap jsonb; ok boolean; begin
 select * into e from ticket_recovery_events where source_id='00000000-0000-4000-8000-000000000001' and stage=1 and channel='email';
 update ticket_recovery_events set status='claimed',claim_id=gen_random_uuid(),claim_expires_at=now()+interval '5 minutes' where id=e.id returning * into e;
 snap:=ticket_recovery_snapshot(e.source_kind,e.source_id);
 update ticket_submissions set representation_paid_at=now() where id=e.source_id;
 perform pg_temp.assert_true(not begin_ticket_recovery_attempt(e.id,e.claim_id,snap),'payment race stopped');
 update ticket_submissions set representation_paid_at=null where id=e.source_id;
 insert into ticket_recovery_suppressions values('email','customer@example.com',now(),'unsubscribe');
 perform pg_temp.assert_true(not begin_ticket_recovery_attempt(e.id,e.claim_id,snap),'unsubscribe stopped at final boundary');
 delete from ticket_recovery_suppressions;
 perform pg_temp.assert_true(begin_ticket_recovery_attempt(e.id,e.claim_id,snap),'valid send reserved');
 perform pg_temp.assert_true(not begin_ticket_recovery_attempt(e.id,e.claim_id,snap),'attempt cannot be retried');
 perform pg_temp.assert_true(not finish_ticket_recovery(e.id,gen_random_uuid(),'sent',null,'fake'),'wrong claim rejected');
 perform pg_temp.assert_true(finish_ticket_recovery(e.id,e.claim_id,'sent',null,'receipt123'),'receipt recorded');
 perform pg_temp.assert_true(not finish_ticket_recovery(e.id,e.claim_id,'sent',null,'fake'),'receipt immutable');
end$$;
-- No anonymous RPC execution or direct data access.
select pg_temp.assert_true(not has_function_privilege('anon','public.ticket_recovery_snapshot(text,uuid)','EXECUTE'),'anonymous snapshot forbidden');
select pg_temp.assert_true(not has_table_privilege('anon','public.ticket_recovery_events','SELECT'),'anonymous outbox forbidden');
select pg_temp.assert_true(not has_function_privilege('authenticated','public.configure_ticket_recovery(boolean,text,integer[])','EXECUTE'),'customer activation forbidden');
select 'ticket recovery SQL lifecycle tests passed' as result;
