project_id = "gcasbisxfrssonllpqrw"

[functions.create-payment]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.ocr-ticket]
verify_jwt = false

[functions.ocr-drivers-license]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.generate-consent-form]
verify_jwt = false

[functions.submit-ticket]
verify_jwt = false

[functions.generate-city-content]
verify_jwt = false

[functions.generate-faqs]
verify_jwt = false

[functions.generate-social-posts]
verify_jwt = false
