import {assertEquals,assertRejects,assertThrows} from 'jsr:@std/assert@1';
import {buildReport,digest,lint,safetyStops,type Json} from './core.ts';
import {paymentEvent,cleanAttribution} from './measurement.ts';
import {execute,type ActionStore} from './platform/actions.ts';

function harness(){
 const payload={holds:[],config:{spendingAuthorized:true,learningSpendLimitCad:2100,campaigns:{'G-Search-Officer':{}},existingCampaignIds:{}},actionHashes:{}} as Json;
 const batch:Json={status:'approved',approved_by:'admin',approved_at:'today',payload,payload_hash:''};
 const input={batchId:'batch',kind:'sync' as const,payload:{sourceHash:'live',operations:[{campaignOperation:{update:{resourceName:'customers/1/campaigns/2',status:'PAUSED'},updateMask:'status'}}]},idempotencyKey:'unique'};
 let mutations=0,uncertain=false,applied=0;const records=new Map<string,Json>();let frozen=false;
 const snapshot={hash:'live',observedAt:new Date().toISOString(),campaigns:[{campaign:{name:'G-Search-Officer',resourceName:'customers/1/campaigns/2'}}]};
 const store:ActionStore={approval:async()=>batch,state:async()=>({paused:false,frozen}),reserve:async(key,batchId,kind,before,payload,rollback)=>{if(records.has(key))return {...records.get(key),duplicate:true};const row={id:key,payload,rollback};records.set(key,row);return row;},finish:async(id,status,after,rollback)=>{if(status==='uncertain')uncertain=true;if(status==='applied')applied++;records.set(id,{...records.get(id),status,after,rollback});}};
 const adapter={snapshot:async()=>snapshot,mutate:async(_operations:Json[],validateOnly=false)=>{if(!validateOnly)mutations++;return {mutateOperationResponses:[]};}};
 const ready=async()=>{payload.actionHashes.sync=await digest(input.payload);batch.payload_hash=await digest(payload);};
 return {store,adapter,input,batch,payload,snapshot,records,ready,setFrozen:()=>{frozen=true;},get mutations(){return mutations;},get uncertain(){return uncertain;},get applied(){return applied;}};
}
Deno.test('frozen hashes survive JSON persistence of omitted optional fields',async()=>{const value={optional:undefined,operations:[{status:'PAUSED',extra:undefined}]};assertEquals(await digest(value),await digest(JSON.parse(JSON.stringify(value))));});
Deno.test('dry run is default and cannot call a provider or reserve an action',async()=>{const h=harness();const r=await execute(h.store,h.adapter,h.input);assertEquals(r.dryRun,true);assertEquals(h.mutations,0);assertEquals(h.records.size,0);});
Deno.test('unapproved batch cannot write',async()=>{const h=harness();await h.ready();h.batch.status='pending';await assertRejects(()=>execute(h.store,h.adapter,{...h.input,dryRun:false}),Error,'EXACT_BATCH_APPROVAL_REQUIRED');assertEquals(h.mutations,0);});
Deno.test('changed frozen payload and arbitrary action cannot bypass approval',async()=>{const h=harness();await h.ready();h.payload.config.learningSpendLimitCad=5000;await assertRejects(()=>execute(h.store,h.adapter,{...h.input,dryRun:false}),Error,'EXACT_BATCH_APPROVAL_REQUIRED');await h.ready();await assertRejects(()=>execute(h.store,h.adapter,{...h.input,payload:{sourceHash:'live',operations:[]},dryRun:false}),Error,'ACTION_NOT_IN_APPROVED_BATCH');});
Deno.test('deduplicates committed writes',async()=>{const h=harness();await h.ready();await execute(h.store,h.adapter,{...h.input,dryRun:false});await execute(h.store,h.adapter,{...h.input,dryRun:false});assertEquals(h.mutations,1);assertEquals(h.applied,1);});
Deno.test('ambiguous writes are held and never automatically resent',async()=>{const h=harness();await h.ready();h.adapter.mutate=async(_ops,validateOnly=false)=>{if(!validateOnly)throw new Error('lost response');return {mutateOperationResponses:[]};};await assertRejects(()=>execute(h.store,h.adapter,{...h.input,dryRun:false}),Error,'UNCERTAIN_PLATFORM_WRITE');assertEquals(h.uncertain,true);const duplicate=await execute(h.store,h.adapter,{...h.input,dryRun:false});assertEquals(duplicate.duplicate,true);});
Deno.test('frozen data and changed source stop discretionary writes',async()=>{const h=harness();await h.ready();h.snapshot.hash='changed';await assertRejects(()=>execute(h.store,h.adapter,{...h.input,dryRun:false}),Error,'LIVE_SOURCE_CHANGED');h.snapshot.hash='live';h.setFrozen();await assertRejects(()=>execute(h.store,h.adapter,{...h.input,dryRun:false}),Error,'ACTIONS_FROZEN');});
Deno.test('pause cannot expand to a different account campaign',async()=>{const h=harness();await h.ready();await assertRejects(()=>execute(h.store,h.adapter,{...h.input,kind:'pause',payload:{operations:[{campaignOperation:{update:{resourceName:'customers/1/campaigns/999',status:'PAUSED'},updateMask:'status'}}]},dryRun:false}),Error,'PAUSE_SCOPE_INVALID');});
Deno.test('spend safety uses inclusive 150 percent and account learning limit',()=>{const config={freshnessMinutes:120,learningSpendLimitCad:2100,campaigns:{officer:{dailyBudgetCad:50},camera:{dailyBudgetCad:20}}};const now=Date.parse('2026-09-27T18:00:00Z');const s={observedAt:new Date(now).toISOString(),date:'2026-09-27',learningSpendCad:100,campaigns:[{name:'officer',status:'ENABLED',spendCad:75,resourceName:'officer'},{name:'camera',status:'ENABLED',spendCad:29.99,resourceName:'camera'}]};assertEquals(safetyStops(config,s,now).length,1);s.learningSpendCad=2100;assertEquals(safetyStops(config,s,now).length,2);s.observedAt=new Date(now-121*60000).toISOString();assertThrows(()=>safetyStops(config,s,now),Error,'STALE_SPEND_DATA');});
Deno.test('actual discounted payments retain tax separately and use a stable ID',()=>{const receipt={id:'cs_test_SYNTHETIC1',mode:'payment',payment_status:'paid',currency:'cad',amount_subtotal:19800,amount_total:16632,total_details:{amount_tax:792,amount_discount:3960},metadata:{ticket_submission_id:'11111111-1111-4111-8111-111111111111'}};const a=paymentEvent(receipt),b=paymentEvent(receipt);assertEquals(a?.event_id,b?.event_id);assertEquals(a?.value_cents,15840);assertEquals(a?.tax_cents,792);assertEquals(paymentEvent({...receipt,payment_status:'unpaid'}),null);});
Deno.test('marketing fields exclude private URLs and unrelated records',()=>{assertEquals(cleanAttribution({gclid:'click123',landing_page:'/portal/cases/private',ticket_number:'ABC123',email:'person@example.com',utm_source:'google',variant_id:'officer_v1'}),{gclid:'click123',utm_source:'google',variant_id:'officer_v1'});});
Deno.test('zero-purchase daily reporting uses unknown spend and honest status',()=>{const r=buildReport([{occurred_at:'2026-09-27T18:00:00Z',event_type:'ticket_uploaded',service:'officer'}],[],'2026-09-27');assertEquals(r.paidStatus,'no paid conversions yet');assertEquals(r.campaigns[0].spendCad,null);assertEquals(r.campaigns[0].costPerPaidClient,null);});
