import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {JSDOM} from 'jsdom';
const built=await build({entryPoints:[new URL('./disclosure-review-ui.ts',import.meta.url).pathname],bundle:true,write:false,format:'iife',globalName:'ReviewUi',platform:'browser'});
function fixture(blocked=false,options={}){const dom=new JSDOM('<main id="disclosure-reviews"></main>',{url:'https://fabsy.ca/admin/portal',runScripts:'dangerously'});const {window:win}=dom;const calls=[];let copied='';Object.defineProperty(win.navigator,'clipboard',{value:{writeText:async x=>{copied=x;}}});win.eval(built.outputFiles[0].text+';window.ReviewUi=ReviewUi;');const p={id:'package',ticket_number:'B21052916C',status:'needs_review',complete_at:'2026-09-26T13:40:00Z',manifest:[{name:'Image1.jpg',sha256:'image'}],draft_text:'Ticket B21052916C — Request for prosecutor review\nPlease consider a total fine of $261.00 or lower.',draft_sha256:'frozen-request-hash',review:{blocked,holds:blocked?['Conflicting date evidence.']:[],observations:[],checklist:[],candidates:[],operator_corrections:[],reference:{filename:'reference.xlsx',version:'version',sha256:'hash'},comparable:{ticket_number:'B44694930C',original_total:381,offered_total:261,speed:96,speed_limit:80,current_total:312,requested_total:261,requested_saving:51,note:'Internal reference only.'}}};if(options.automatic){p.status=options.submitted?'submitted':'approved';p.review_submission_job_id='submission-job';p.client_update_draft_id=options.submitted?'client-draft':null;}win.ReviewUi.renderDisclosureReviews({disclosureReviews:[p],disclosureDocuments:[],portalTerms:options.missingTerms?null:{sha256:'verified-terms-hash',effective_date:'2025-03-13',text:'Government terms captured from the official portal.',url:'https://traffictickets.alberta.ca/terms-of-use'}},async(action,values)=>{calls.push(JSON.parse(JSON.stringify({action,...values})));if(options.fail)throw new Error('Approval changed. Refresh.');},async()=>{},()=>{});return {dom,win,calls,p,copied:()=>copied};}
const settle=async()=>{for(let i=0;i<5;i++)await new Promise(r=>setImmediate(r));};
test('copying the government request excludes the internal comparable and cannot approve or submit',async()=>{const f=fixture();try{[...f.win.document.querySelectorAll('button')].find(x=>x.textContent==='Copy request text').click();await settle();assert.equal(f.copied(),f.p.draft_text);assert.equal(f.copied().includes('B44694930C'),false);assert.deepEqual(f.calls,[]);}finally{f.dom.window.close();}});
test('one unchecked checkbox saves combined request, terms and submission approval with one click',async()=>{const f=fixture();try{const form=f.win.document.querySelector('form');const boxes=form.querySelectorAll('input[type=checkbox]');assert.equal(boxes.length,1);assert.equal(boxes[0].checked,false);assert.equal(form.querySelector('button'),null);assert.match(form.textContent,/signer authority/);assert.match(form.textContent,/accept the government terms/);assert.match(form.textContent,/submit this request/);assert.deepEqual(f.calls,[]);boxes[0].click();boxes[0].click();await settle();assert.deepEqual(f.calls,[{action:'approve-disclosure-review',id:'package',hash:'frozen-request-hash',attestations:{confirmed:true,version:'review-and-terms-v1',terms_sha256:'verified-terms-hash',scope:'exact_review_request'}}]);}finally{f.dom.window.close();}});
test('failed approval clears the checkbox and permits an explicit retry',async()=>{const f=fixture(false,{fail:true});try{const box=f.win.document.querySelector('input');box.click();await settle();assert.equal(box.checked,false);assert.equal(box.disabled,false);assert.equal(f.calls.length,1);}finally{f.dom.window.close();}});
test('missing government terms prevents approval',()=>{const f=fixture(false,{missingTerms:true});try{assert.equal(f.win.document.querySelector('form'),null);assert.match(f.win.document.body.textContent,/terms must be available/);assert.deepEqual(f.calls,[]);}finally{f.dom.window.close();}});
test('a blocked extraction cannot expose approval controls even if stale draft text remains',()=>{const f=fixture(true);try{assert.equal(f.win.document.querySelector('form'),null);assert.match(f.win.document.body.textContent,/Conflicting date/);assert.deepEqual(f.calls,[]);}finally{f.dom.window.close();}});

test('an approved cloud request exposes its job without a second manual filing form',()=>{const f=fixture(false,{automatic:true});try{assert.equal(f.win.document.querySelector('form'),null);assert.match(f.win.document.body.textContent,/Government submission: queued/);assert.equal([...f.win.document.querySelectorAll('a')].find(a=>a.textContent==='Open submission job').getAttribute('href'),'/admin/portal?job=submission-job');assert.equal(f.calls.length,0);}finally{f.dom.window.close();}});
test('confirmed cloud submission links the existing exact-client send-approval queue',()=>{const f=fixture(false,{automatic:true,submitted:true});try{assert.match(f.win.document.body.textContent,/Government submission confirmed/);assert.equal([...f.win.document.querySelectorAll('a')].find(a=>a.textContent==='Review client status update').getAttribute('href'),'/admin/portal?draft=client-draft');assert.equal(f.calls.length,0);}finally{f.dom.window.close();}});
