import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {canonicalTerms,digest,verifyTicketPage,existingReview,reviewReceipt,resumePageIndex} from './review-submit-policy.mjs';import {portalTarget} from './portal-policy.mjs';
const terms=JSON.parse(readFileSync(new URL('../../docs/alberta-portal-terms-2025-03-13.json',import.meta.url)));
const packet={ticket_number:'B21052916C',defendant:'DOME PRODUCTIONS INC',proposal:{original_total:312}};
test('entire current government terms match frozen approval despite layout whitespace',async()=>{assert.equal(await digest(canonicalTerms('Navigation\n'+terms.text+'\nBack')),terms.sha256);assert.equal(await digest(canonicalTerms(terms.text.replaceAll('\n','  '))),terms.sha256);assert.notEqual(await digest(canonicalTerms(terms.text.replace('Users are responsible','Everyone is responsible'))),terms.sha256);assert.throws(()=>canonicalTerms('Sign in to read terms'));});
test('ticket, legal defendant and original fine are independently checked',()=>{const page='Ticket number B21052916C Name / Registered Owner DOME PRODUCTIONS INC Total $312.00';verifyTicketPage(page,packet,true);for(const text of [page.replace('B21052916C','B44694930C'),page.replace('DOME PRODUCTIONS INC','Gord Hicks'),page.replace('$312.00','$381.00')])assert.throws(()=>verifyTicketPage(text,packet,true));});
test('an existing pending review prevents another submission',()=>{for(const t of ['View your review','Review has been submitted','Request for review is pending','Prosecutor review requested'])assert.equal(existingReview(t),true);assert.equal(existingReview('Request a review — request a different charge or lesser penalty'),false);});
test('confirmation requires the actual official receipt page, success and exact ticket',()=>{const text='Review received. We have received your request to review ticket B21052916C';assert.equal(reviewReceipt('https://traffictickets.alberta.ca/dispute-received',text,packet.ticket_number).source,'cloud_verified_review');for(const [url,t] of [['https://evil.test/dispute-received',text],['https://traffictickets.alberta.ca/submit-your-dispute',text],['https://traffictickets.alberta.ca/ticket-penalty-and-options',text],['https://traffictickets.alberta.ca/another-page',text],['https://traffictickets.alberta.ca/dispute-received',text.replace('B21052916C','B44694930C')],['https://traffictickets.alberta.ca/dispute-received','Review request B21052916C needs your signature']])assert.throws(()=>reviewReceipt(url,t,packet.ticket_number));});
test('approved writes may open only exact ticket search, never acceptance or payment',()=>{const j={action:'submit_review_request',ticket_number:packet.ticket_number,source_url:'https://traffictickets.alberta.ca/ticket-number-search?ticketNumber=B21052916C'};assert.equal(portalTarget(j),j.source_url);for(const source_url of [j.source_url+'&submit=true',j.source_url.replace('B21052916C','B44694930C'),'https://traffictickets.alberta.ca/pay-ticket'])assert.throws(()=>portalTarget({...j,source_url}));});

test('resumption selects the sole official ticket page, regardless of blank page order',()=>{const actual='https://traffictickets.alberta.ca/search-verification';assert.equal(resumePageIndex(['about:blank',actual]),1);assert.equal(resumePageIndex([actual,'about:blank','https://traffictickets.alberta.ca/terms-of-use']),0);assert.throws(()=>resumePageIndex(['about:blank']));assert.throws(()=>resumePageIndex([actual,'https://traffictickets.alberta.ca/submit-your-dispute']));});
