import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {JSDOM} from 'jsdom';import {readFileSync} from 'node:fs';import {digest} from './review-submit-policy.mjs';
const built=await build({entryPoints:[new URL('./review-submit.ts',import.meta.url).pathname],bundle:true,keepNames:true,write:false,format:'esm',platform:'node'});const {executeApprovedReview}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
const terms=JSON.parse(readFileSync(new URL('../../docs/alberta-portal-terms-2025-03-13.json',import.meta.url)));
const radio=(text,name)=>`<label><input type=radio name="${name}">${text}</label>`;
const check=text=>`<label><input type=checkbox>${text}</label>`;
const draft='Ticket B21052916C — Request for prosecutor review\nPlease reduce the total fine by $100.00 to $212.00 inclusive of surcharge.';
const packet={ticket_number:'B21052916C',defendant:'DOME PRODUCTIONS INC',draft_text:draft,draft_sha256:await digest(draft),source_sha256:'source',consent_sha256:'consent',plate:'TESTPLATE',terms:{sha256:terms.sha256},consent:{name:'Signed consent - B21052916C.pdf',data:Buffer.from('%PDF-fixture').toString('base64')},representative:{name:'Brett Bilon',business:'Fabsy Traffic Ticket Services',email:'hello@fabsy.ca'},proposal:{original_total:312}};
class Page{
 constructor(options={},stage='/ticket-number-search',owner){this.options=options;this.owner=owner||this;this.clicks=[];this.snapshots=[];this.termReads=0;this.load(stage);}
 load(stage){this.stage=stage;this.dom?.window.close();const identity=`Ticket B21052916C Name / Registered Owner ${this.options.wrongCase?'OTHER INC':'DOME PRODUCTIONS INC'} Total $312.00`;
 const form=`<h1>Submit your review</h1>${radio('No, this is not my ticket, but I am an agent/lawyer acting on behalf of the defendant','ticket')}${radio('Agent','role')}<input id=fullName><input name=lawFirm><input id=email type=email>${check('No email address')}<input id=defendantEmail><textarea id=disputeDetails></textarea><input id=disputeUpload type=file>${check('I confirm that all the information supplied is accurate and truthful.')}${this.options.newDeclaration?check('I accept a plea'):''}<a>Ticket penalty and payment options</a><button>Submit</button>`;
 const html=stage==='/terms-of-use'?`<pre>${terms.text}${this.options.changedTerms?' changed legal terms':''}</pre>`:stage==='/ticket-number-search'?`<input id=ticketNumber><input type=email>${check('I agree to the Terms and Conditions.')}<input type=submit value=Next>`:stage==='/search-verification'?`Ticket number B21052916C ${radio('Licence plate','search')}<label for=licencePlate>Licence plate</label><input id=licencePlate><input type=submit value="Find ticket">`:stage==='/ticket-information'?identity+'<a>Next</a>':stage==='/ticket-penalty-and-options'?identity+(this.options.existing?' Review has been submitted':'')+'<button>Additional Options</button>':stage==='/dispute-options'?'Ticket B21052916C <button>Request a review</button>':stage==='/submit-your-dispute'?form:'Review received. We have received your request to review ticket B21052916C';
 this.dom=new JSDOM('<main>'+html+'</main>',{url:'https://traffictickets.alberta.ca'+stage,runScripts:'dangerously'});const w=this.dom.window;
 Object.defineProperty(w.HTMLElement.prototype,'innerText',{get(){return this.textContent;}});w.Element.prototype.getBoundingClientRect=()=>({width:100,height:60});
 class Transfer{constructor(){this.files=[];this.items={add:f=>this.files.push(f)};}}w.DataTransfer=Transfer;
 const upload=w.document.querySelector('#disputeUpload');if(upload){Object.defineProperty(upload,'files',{value:[],writable:true});upload.addEventListener('change',()=>{const name=w.document.createElement('p');name.textContent=upload.files[0].name;w.document.querySelector('main').append(name);});}
 for(const el of w.document.querySelectorAll('button,a,input[type=submit]'))el.addEventListener('click',()=>{const label=el.textContent||el.value;this.clicks.push(label);if(label==='Submit'){this.snapshots.push({draft:w.document.querySelector('#disputeDetails').value,email:w.document.querySelector('#email').value,defendantEmail:w.document.querySelector('#defendantEmail').value,upload:upload.files[0].name});el.textContent='Confirm review';const prompt=w.document.createElement('p');prompt.textContent=this.options.changedConfirmation?'Accept this plea?':'Are you sure you want to submit this review?';w.document.querySelector('main').append(prompt);}else if(label==='Confirm review'){if(!this.options.interrupted)this.load('/dispute-received');}else this.load({'Next':stage==='/ticket-number-search'?'/search-verification':'/ticket-penalty-and-options','Find ticket':'/ticket-information','Additional Options':'/dispute-options','Request a review':'/submit-your-dispute','Ticket penalty and payment options':'/ticket-penalty-and-options'}[label]);});
 }
 url(){return 'https://traffictickets.alberta.ca'+this.stage;}
 async evaluate(fn,arg){this.dom.window.__arg=arg;return this.dom.window.eval('('+fn.toString()+')(__arg)');}
 async waitForFunction(fn,opts,arg){if(!await this.evaluate(fn,arg))throw new Error('WAIT_FAILED');}
 async $(selector){const e=this.dom.window.document.querySelector(selector);return e?{click:async()=>{e.value='';},type:async value=>{e.value=value;}}:null;}
 browser(){return {newPage:async()=>{this.termReads++;return new Page(this.options,'/terms-of-use',this);}};}
 async goto(){return {status:()=>200};}async close(){this.dom.window.close();}
}
test('cloud flow submits frozen request and actual consent once as agent with no defendant email',async()=>{const page=new Page();const calls=[];try{await executeApprovedReview(page,packet,async f=>calls.push(['commit',f]),async r=>calls.push(['receipt',r]));assert.deepEqual(calls.map(c=>c[0]),['commit','receipt']);assert.equal(page.clicks.filter(c=>c==='Submit').length,1);assert.equal(page.clicks.filter(c=>c==='Confirm review').length,1);assert.deepEqual(page.snapshots,[{draft,email:'hello@fabsy.ca',defendantEmail:'',upload:packet.consent.name}]);assert.equal(calls[0][1].consent_sha256,'consent');assert.equal(calls[1][1].ticket_number,packet.ticket_number);assert.equal(page.termReads,2);}finally{await page.close();}});
test('wrong case, existing review, changed terms and new declaration all hold before committing',async()=>{for(const options of [{wrongCase:true},{existing:true},{changedTerms:true},{newDeclaration:true}]){const page=new Page(options);let commits=0;try{await assert.rejects(executeApprovedReview(page,packet,async()=>commits++,async()=>{}));assert.equal(commits,0);assert.equal(page.clicks.includes('Submit'),false);}finally{await page.close();}}});
test('interrupted final submission does not retry or create a success receipt',async()=>{const page=new Page({interrupted:true});let commits=0,receipts=0;try{await assert.rejects(executeApprovedReview(page,packet,async()=>commits++,async()=>receipts++));assert.equal(commits,1);assert.equal(receipts,0);assert.equal(page.clicks.filter(x=>x==='Submit').length,1);assert.equal(page.clicks.filter(x=>x==='Confirm review').length,1);}finally{await page.close();}});
test('a resumed form rechecks the current legal defendant before submitting',async()=>{const page=new Page({wrongCase:true},'/submit-your-dispute');let commits=0;try{await assert.rejects(executeApprovedReview(page,packet,async()=>commits++,async()=>{}),/LIVE_TICKET_IDENTITY_MISMATCH/);assert.equal(page.clicks[0],'Ticket penalty and payment options');assert.equal(commits,0);assert.equal(page.clicks.includes('Submit'),false);}finally{await page.close();}});

test('SPA route changes wait for the new verification and confirmation content',async()=>{
 class Delayed extends Page{load(stage){if(this.dom){this.stage=stage;this.pending=stage;this.dom.reconfigure({url:'https://traffictickets.alberta.ca'+stage});}else super.load(stage);}async waitForFunction(fn,opts,arg){if(!await this.evaluate(fn,arg)&&this.pending){const pending=this.pending;this.pending=null;super.load(pending);this.waited=(this.waited||0)+1;}return super.waitForFunction(fn,opts,arg);}}
 const page=new Delayed();let receipt;try{await executeApprovedReview(page,packet,async()=>{},async r=>receipt=r);assert.equal(receipt.ticket_number,packet.ticket_number);assert.equal(page.clicks.filter(x=>x==='Submit').length,1);assert.ok(page.waited>=6);}finally{await page.close();}
});

test('changed final confirmation is held without the consequential click',async()=>{const page=new Page({changedConfirmation:true});let commits=0,receipts=0;try{await assert.rejects(executeApprovedReview(page,packet,async()=>commits++,async()=>receipts++),/REVIEW_CONFIRMATION_CHANGED/);assert.equal(commits,1);assert.equal(receipts,0);assert.equal(page.clicks.includes('Confirm review'),false);}finally{await page.close();}});
