import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {JSDOM} from 'jsdom';
const built=await build({entryPoints:[new URL('./session-terms-ui.ts',import.meta.url).pathname],bundle:true,write:false,format:'iife',globalName:'sessionUI',platform:'browser'});
function fixture(overrides={},admin=true){const dom=new JSDOM('<article></article>',{runScripts:'dangerously'});dom.window.eval(built.outputFiles[0].text+';window.sessionUI=sessionUI;');const card=dom.window.document.querySelector('article'),calls=[];let work;
 const job={id:'job',status:'needs_review',result:{phase:'awaiting_terms',session_record_id:'session'}};
 const session={id:'session',browser_session_id:'actual-browser',terms_sha256:'frozen-terms-hash',terms_text:'Actual government terms <script>window.bad=true</script>',status:'pending',expires_at:new Date(Date.now()+600000).toISOString(),scope:[{job_id:'job',ticket_number:'T12345678Z',action:'submit_initial_disclosure'}],...overrides};
 dom.window.sessionUI.renderSessionTerms(card,job,{portalSessions:[session],sessionAdministrator:admin},async(action,values)=>{calls.push({action,...values});},(button,callback)=>{if(button.disabled)return;button.disabled=true;work=callback();},()=>{});
 return {dom,card,calls,settle:()=>work};}
test('rendering or opening the terms does not accept; one administrator tap freezes session and hash',async()=>{const f=fixture();try{assert.equal(f.calls.length,0);assert.match(f.card.textContent,/T12345678Z/);assert.match(f.card.textContent,/actual-browser/);assert.equal(f.dom.window.bad,undefined);const button=f.card.querySelector('button');button.click();button.click();await f.settle();assert.deepEqual(f.calls,[{action:'session-accept',id:'session',hash:'frozen-terms-hash'}]);}finally{f.dom.window.close();}});
test('expired sessions offer a new session and never accept old terms',async()=>{const f=fixture({expires_at:new Date(Date.now()-1000).toISOString()});try{assert.equal(f.card.querySelector('button').textContent,'Start a new session');f.card.querySelector('button').click();await f.settle();assert.deepEqual(f.calls,[{action:'handoff',id:'job'}]);}finally{f.dom.window.close();}});
test('a case manager sees the terms but cannot accept',()=>{const f=fixture({},false);try{assert.equal(f.card.querySelector('button'),null);assert.match(f.card.textContent,/administrator must accept/);assert.equal(f.calls.length,0);}finally{f.dom.window.close();}});
