name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Sync pages from Supabase (guarded)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          if [ -z "${SUPABASE_URL}" ] || [ -z "${SUPABASE_SERVICE_ROLE_KEY}" ]; then
            echo "Supabase secrets not set; skipping sync."
            exit 0
          fi
          node scripts/sync-pages-from-db.js
      
      - name: Generate routes
        run: node scripts/generate-routes.js
      
      - name: Validate FAQ JSON-LD equality
        run: node ci/validate-faq-jsonld.js
      
      - name: Build (SSG)
        run: npm run build
      
      # Add your deployment step here
      # - name: Deploy
      #   run: npm run deploy
